### PR TITLE
example "xlsx2adoc"

### PR DESCRIPTION
**Pull request by mschnell1**
issue #10

### CODE REVIEW

**Review by mschnell1 — COMMENTED** [review]
trying tocreate a pull request

**Comment by MortalreminderPT** [comment]
It looks like your code is not passing workflow and you can see the log in [action](https://github.com/MortalreminderPT/edit-xlsx/actions/runs/8753661151/job/24027769330#step:4:2198). 
But perhaps I can explain why for you. To ensure the accuracy of each example, I asked it in workflow to execute all .rs file under examples.
One possible solution is that you could integrate both mods created all together in the xlsx2adoc.rs

**Comment by MortalreminderPT** [comment]
I merged your example into the dev-0.4 branch and then I'll fix this little problem.
Thank you for your contribution to this project.😉

**Comment by mschnell1** [comment]
> I merged your example into the dev-0.4 branch and then I'll fix this little problem. Thank you for your contribution to this project.😉
Great !
I intended to ask if it's even appropriate to use multiple files in an example..
I guess it's not.

**Comment by MortalreminderPT** [comment]
> > I merged your example into the dev-0.4 branch and then I'll fix this little problem. Thank you for your contribution to this project.😉
> > Great !
> > I intended to ask if it's even appropriate to use multiple files in an example..
> > I guess it's not.

Yep you can use all the xlsx files under `tests/xlsx`, if examples gets complicated in the future maybe I'll need to split it into simple and complex examples later on

**Pull request merged**
