### PR TITLE
Dev 0.4 mschnell

### PR DESCRIPTION
**Pull request by mschnell1**

### CODE REVIEW

**Comment by mschnell1** [comment]
Creates a runtime error in a library function.

**Comment by MortalreminderPT** [comment]
When I tested your example with several complex xlsx files under `tests/xlsx`, I found that there was an out-of-bounds problem with the modification of the widths, because the upper limit of the col range could exceed the length of the widths.
I think this can be solved by passing in the max allowed upper limit when [decoding the range](https://github.com/MortalreminderPT/edit-xlsx/blob/f4436d82e183ee889b4f758b67a5338cf8a6ba16/examples/xlsx2adoc.rs#L56C1-L65C2).
Additionally, I think your project is useful and valuable, do you plan to open source this project to your own repository?

**Comment by mschnell1** [comment]
Right now I don't plan to manage projects on Github, as in the company we use a private Gitlab server for all our software. 
So I could either work on forks or directly push commits to the main project, if appropriate.

**Comment by mschnell1** [comment]
> the upper limit of the col range could exceed the length of the widths. I think this can be solved by passing in the max allowed upper limit 

Hmm I thought this should not happen.... Of course using max is save to avoid a panic, but do we loss some viable case with that ?

**Pull request merged**
